config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :contacts
  mount LetterOpenerWeb::Engine, at: "/inbox" 
  resources :sessions
  resources :favorites
  resources :users do
    collection do
      post :confirm
    end
  end  
  resources :blogs do
    collection do
      post :confirm
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_many :blogs
  has_many :favorites, dependent: :destroy

  mount_uploader :image, ImageUploader

  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :barrier_user, only: [:edit, :destroy]
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new  
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      ContactMailer.contact_mail(@blog).deliver
      redirect_to blogs_path
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit   
    end  
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
  def barrier_user
    unless Blog.find_by(id: params[:id]).user_id == current_user.id
      flash[:notice] = "あなたは編集できません"
      redirect_to blogs_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contacts_path, notice: '問い合わせは完了しました'
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.all
  end

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password]) #authenticateはパスワードが一致してるか判定するメソッド
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end  
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :correct_user, only: [:edit, :destroy]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else  
      if @user.save
        redirect_to users_path    
      else
        render :new
      end
    end  
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path(user_params)
    else
      render :edit  
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(params[:id]) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' 
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) 
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit ) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "件") %>のエラーがあるので確認してください</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text_field">
    <%= form.label :文書 %>
    <%= form.text_area :content %>
  </div>

  <div class="image_field">
    <%= form.label :画像 %>
    <%= image_tag(blog.image.url) if blog.image && blog.image.url %>
    <%= form.file_field  :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<header>
<h1>確認画面</h1>
</header>

<h3>以下の内容で投稿しますか？</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@blog, url:new_blog_path, local: true, method: "get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

<footer>
<p>fakebook</p>
</footer>

app/views/blogs/edit.html.erb
<header>
<h1>編集画面</h1>
</header>

<%= render 'form', blog: @blog %>
<%= link_to '投稿一覧へ戻る', blogs_path %>

<footer>
<p>fakebook</p>
</footer>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<header>
<h1>投稿一覧</h1>
</header>

<table>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>文書</th>
      <th>画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.user.name %></td>
        <td><%= blog.content %></td>
        <td><%= image_tag blog.image.url unless blog.image.url == nil %></td>
        <td><%= link_to '投稿詳細', blog %></td>
        <% if logged_in? && current_user.id == blog.user_id %>
          <td><%= link_to '投稿を編集する', edit_blog_path(blog) %></td>
          <td><%= link_to '投稿を削除する', blog, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規投稿画面へ', new_blog_path %>


<footer>
<p>fakebook</p>
</footer>

app/views/blogs/new.html.erb
<header>
<h1>新規投稿画面</h1>
</header>

<%= render 'form', blog: @blog %>
<%= link_to '投稿一覧画面へ', blogs_path %>

<footer>
<p>fakebook</p>
</footer>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>投稿内容</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>写真</strong>
  <%= image_tag @blog.image.url if @blog.image.url %>
</p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to '投稿を編集する', edit_blog_path(@blog) %> |
<%= link_to '投稿一覧に戻る', blogs_path %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :名前 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :メールアドレス %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :問い合わせ内容 %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<header>
<h1>問い合わせ一覧</h1>
</header>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to '問い合わせ内容', contact %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '問い合わせる', new_contact_path %>


<footer>
<p>fakebook</p>
</footer>

app/views/contacts/new.html.erb
<header>
<h1>問い合わせページ</h1>
</header>

<%= render 'form', contact: @contact %>
<%= link_to '問い合わせ一覧へ', contacts_path %>

<footer>
<p>fakebook</p>
</footer>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<header>
<h1>問い合わせ詳細</h1>
</header>

<p>
  <strong>名前:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>問い合わせ内容:</strong>
  <%= @contact.content %>
</p>


<%= link_to '問い合わせ一覧へ戻る', contacts_path %>


<footer>
<p>fakebook</p>
</footer>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>
<header>
<h1>お気に入り一覧</h1>
</header>

<table>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>投稿内容</th>
      <th>画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.name %></td>
        <td><%= favorite.blog.content %></td>
        <td><%= image_tag favorite.blog.image.url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '投稿一覧へ', blogs_path %>
<%= link_to '新規投稿へ', new_blog_path %>

<footer>
<p>fakebook</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "プロフィールページ", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "新規登録はこちら", new_user_path %>
      <%= link_to "ログイン画面", new_session_path %>
    <% end %>  
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "個") %>のエラーがあるので、確認してください。</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if action_name == 'edit' %>
    <%= form.label :プロフィール画像 %>
    <%= form.file_field :image %>
    <% end %>
  </div>

  <div class="name_field">
    <%= form.label :名前 %>
    <%= form.text_field :name %>
  </div>

  <div class="email_field">
    <%= form.label :メールアドレス %>
    <%= form.email_field :email %>
  </div>

  <div class="field_password">
    <%= form.label :パスワード %>
    <%= form.password_field :password %>
  </div>
  
  <div class="field">
    <%= form.label :パスワード確認画面 %>
    <%= form.password_field :password %>
  </div>
 
  <div class="actions">
    <%= form.submit :登録する %>
  </div>
<% end %>

app/views/users/edit.html.erb
<header>
<h1>プロフィール編集ページ</h1>
</header>

<%= render 'form', user: @user %>
<%= link_to 'ユーザ一覧へ', users_path %>

<footer>
<p>fakebook</p>
</footer>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>登録者のページ</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to '詳細画面へ', user %></td>
        <td><%= link_to '編集画面へ', edit_user_path(user) %></td>
        <td><%= link_to '削除する', user_path(user.id), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '投稿画面へ', new_blog_path %>

app/views/users/new.html.erb
<header>
<h1>新規登録画面</h1>
</header>

<%= render 'form', user: @user %>

<footer>
<p>fakebook</p>
</footer>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<header>
<h1><%= @user.name %>の詳細ページ</h1>
</header>

<p>
  <strong>あなたの写真</strong>
  <%= image_tag @user.image.url unless @user.image.url == nil%>
</p>

<p>
  <strong>あなたの名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>あなたのメールアドレス:</strong>
  <%= @user.email %>
</p>

<%= link_to '新規投稿する', new_blog_path %> 
<%= link_to 'プロフィールを変更する', edit_user_path %> 
<%= link_to 'お気に入り一覧ページへ', favorites_path %>
<%= link_to '問い合わせページへ', new_contact_path %>


<footer>
<p>fakebook</p>
</footer>